version: '2.1'
services:
  app-server:
    build:
      context: rebeca_server
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATASOURCE_USERNAME: REBECA
      DATASOURCE_PASSWORD: REBECA_APP
      DATASOURCE_HOST: db
      PROFILE: prd
    networks:
      rebeca:
        ipv4_address: 172.19.0.2
  db:
    image: truevoly/oracle-12c
    ports:
      - '8082:8080'
      - '1521:1521'
      - '27017:27017'
    environment:
      - ORACLE_PWD=Oracle
      - ORACLE_ALLOW_REMOTE=true
    networks:
      rebeca:
        ipv4_address: 172.19.0.3
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          if [ "`echo \"SELECT ACCOUNT_STATUS FROM DBA_USERS WHERE USERNAME = 'ANONYMOUS' AND ACCOUNT_STATUS = 'EXPIRED';\"|/u01/app/oracle/product/12.1.0/xe/bin/sqlplus -S sys/oracle as sysdba|grep ACCOUNT_STATUS`" = "ACCOUNT_STATUS"
          ];then true;else false;fi
      timeout: 3s
      interval: 30s
      retries: 30
    volumes:
      - './db-data:/var/lib/mysql'
      - './rebeca_server/src/main/resources/db/migration:/docker-entrypoint-initdb.d'
  angular:
    build:
      context: rebeca-front
      dockerfile: Dockerfile
    networks:
      rebeca:
        ipv4_address: 172.19.0.4
    ports:
      - '4200:80'
      
volumes:
  db-data:
    driver: local
networks:
  rebeca:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1
