version: '2.1'
services:
  app-server:
    build:
      context: rebeca_server
      dockerfile: Dockerfile
    ports:
      - '80:80'
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATASOURCE_USERNAME: REBECA
      DATASOURCE_PASSWORD: REBECA_APP
      DATASOURCE_HOST: db
      PROFILE: prd
    networks:
      - backend
      - frontend
  db:
    image: truevoly/oracle-12c
    ports:
      - '8082:8080'
      - '1521:1521'
      - '27017:27017'
    environment:
      - ORACLE_PWD=Oracle
      - ORACLE_ALLOW_REMOTE=true
    networks:
      - backend
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          if [ "`echo \"SELECT ACCOUNT_STATUS FROM DBA_USERS WHERE USERNAME = 'ANONYMOUS' AND ACCOUNT_STATUS = 'EXPIRED';\"|/u01/app/oracle/product/12.1.0/xe/bin/sqlplus -S sys/oracle as sysdba|grep ACCOUNT_STATUS`" = "ACCOUNT_STATUS"
          ];then true;else false;fi
      timeout: 3s
      interval: 30s
      retries: 30
    volumes:
      - './db-data:/var/lib/mysql'
      - './rebeca_server/src/main/resources/db/migration:/docker-entrypoint-initdb.d'
#  angular:
#    build:
#      context: rebeca_front
#      dockerfile: Dockerfile
#    ports:
#      - '8080:8080'
      
volumes:
  db-data:
    driver: local
networks:
  backend: null
  frontend: null
