version: '3.7'

# Definindo os serviços
services:
  # Serviço para o backend
    app-server:
        build:
            context: rebeca_server # Imagem criada pelo Dockerfile que está na raiz do projeto 
            dockerfile: Dockerfile
        ports:
            - "8082:8081" 
        restart: always
        depends_on: 
            - db # Banco de dados Oracle
        environment: 
            DATASOURCE_USERNAME: REBECA
            DATASOURCE_PASSWORD: REBECA_APP
            DATASOURCE_HOST: db
        networks: # Redes entre os serviços (os serviços na mesma rede podem se comunicar uns com os outros usando seu nome)
            - backend
            - frontend


# Serviço para o front end
#  app-client:
#    build:
#      context: rebeca_client # Use an image built from the specified dockerfile in the `polling-app-client` directory.
#      dockerfile: Dockerfile
#      args:
#        REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api
#    ports:
#      - "9090:80" 
#    restart: always
#    depends_on:
#      - app-server
#    networks:
#      - frontend  

# Serviço para o banco de dados Oracle
    db:
        image: truevoly/oracle-12c #Baseado na imagem https://github.com/MaksymBilenko/docker-oracle-12c
        ports: 
            - "8080:8080"
            - "1521:1521"
            - "27017:27017"
        environment:
            - ORACLE_PWD=Oracle
        networks:
            - backend  
        volumes:
            - ./db-data:/var/lib/mysql
            - ./rebeca_server/src/main/resources/db/migration:/docker-entrypoint-initdb.d # recupera todos os scripts que deverão ser executados logo no inicio do serviço
            
# Volumes
volumes:
    db-data: 
        driver: local
        

# Networks to be created to facilitate communication between containers
networks:
    backend:
    frontend:    
