-- USER SQL
CREATE USER "REBECA" IDENTIFIED BY "REBECA_APP"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "REBECA" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "REBECA" ;
GRANT SELECT ANY TABLE  TO "REBECA";
-- SYSTEM PRIVILEGES

