-- USER SQL
CREATE USER "REBECA" IDENTIFIED BY "rebeca_app"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "REBECA" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "REBECA" ;

-- SYSTEM PRIVILEGES

