-- USER SQL
CREATE USER CO IDENTIFIED BY "CO_APP"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "CO" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "CO";
GRANT SELECT ANY TABLE  TO "CO";
-- SYSTEM PRIVILEGES
